{
	"name": "AliceSatellite",
	"icon": "fas fa-satellite",
	"version": "1.3.4",
	"category": "alice",
	"author": "ProjectAlice",
	"maintainers": [
		"Psycho",
		"Jierka",
		"maxbachmann",
		"philipp2310"
	],
	"desc": "AliceSatellite is the official skill to support Project Alice satellites",
	"aliceMinVersion": "1.0.0-b1",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de",
			"it"
		]
	}
}
